#include "../include/dsmil_micro_model.h"
#include <string.h>
#include <math.h>

/* This header is automatically generated by scripts/train_synthetic_model.py */
#include "dsmil_model_weights.h"

void dsmil_micro_model_init(void) {
    /* Weights are statically compiled from dsmil_model_weights.h */
}

/* Very simple hash function for character trigrams (Feature Hashing Trick) */
static inline int hash_trigram(char a, char b, char c) {
    unsigned int h = 2166136261u;
    h = (h ^ (unsigned int)a) * 16777619u;
    h = (h ^ (unsigned int)b) * 16777619u;
    h = (h ^ (unsigned int)c) * 16777619u;
    return h % DSMIL_MODEL_INPUT_DIM;
}

/* Extract feature vector from context text */
static void extract_features(const char* text, float* vector) {
    size_t len = strlen(text);
    if (len < 3) return;
    
    for (size_t i = 0; i < len - 2; i++) {
        int idx = hash_trigram(text[i], text[i+1], text[i+2]);
        vector[idx] += 1.0f;
    }
}

dsmil_classification_t dsmil_micro_model_infer(const dsmil_model_context_t* ctx, float out_scores[DSMIL_MODEL_NUM_CLASSES]) {
    float x[DSMIL_MODEL_INPUT_DIM] = {0};
    
    /* 1. Feature Extraction (Hashing Trick) on Pre and Post context */
    extract_features(ctx->pre_context, x);
    extract_features(ctx->post_context, x);
    
    /* Normalize the input vector to prevent explosive activations */
    float sum = 0.0f;
    for (int i = 0; i < DSMIL_MODEL_INPUT_DIM; i++) sum += x[i];
    if (sum > 0.0f) {
        for (int i = 0; i < DSMIL_MODEL_INPUT_DIM; i++) x[i] /= sum;
    }
    
    /* 2. Hidden Layer (Dense + ReLU) */
    float hidden[DSMIL_MODEL_HIDDEN_DIM] = {0};
    for (int i = 0; i < DSMIL_MODEL_HIDDEN_DIM; i++) {
        float val = MODEL_B1[i];
        for (int j = 0; j < DSMIL_MODEL_INPUT_DIM; j++) {
            val += x[j] * MODEL_W1[j][i];
        }
        hidden[i] = val > 0 ? val : 0; /* ReLU */
    }
    
    /* 3. Output Layer (Dense) */
    float max_score = -1e9;
    int best_class = 0;
    
    for (int i = 0; i < DSMIL_MODEL_NUM_CLASSES; i++) {
        float val = MODEL_B2[i];
        for (int j = 0; j < DSMIL_MODEL_HIDDEN_DIM; j++) {
            val += hidden[j] * MODEL_W2[j][i];
        }
        out_scores[i] = val;
        if (val > max_score) {
            max_score = val;
            best_class = i;
        }
    }
    
    /* 4. Softmax */
    float exp_sum = 0.0f;
    for (int i = 0; i < DSMIL_MODEL_NUM_CLASSES; i++) {
        out_scores[i] = expf(out_scores[i] - max_score); /* numerical stability */
        exp_sum += out_scores[i];
    }
    for (int i = 0; i < DSMIL_MODEL_NUM_CLASSES; i++) {
        out_scores[i] /= exp_sum;
    }
    
    return (dsmil_classification_t)best_class;
}
