#include "../include/dsmil_micro_model.h"
#include <string.h>
#include <math.h>

/* This header is auto-generated by scripts/train_from_sample.py */
#include "dsmil_model_weights.h"

void dsmil_micro_model_init(void) {
    /* Weights are statically compiled from dsmil_model_weights.h. No-op at runtime. */
}

/* FNV-1a trigram hash → feature index */
static inline int hash_trigram(char a, char b, char c) {
    unsigned int h = 2166136261u;
    h = (h ^ (unsigned int)(unsigned char)a) * 16777619u;
    h = (h ^ (unsigned int)(unsigned char)b) * 16777619u;
    h = (h ^ (unsigned int)(unsigned char)c) * 16777619u;
    return (int)(h % 256u);
}

/*
 * Extract 260-dimensional feature vector from a text buffer:
 *   [0..255]  character trigram hashing counts (normalized)
 *   [256]     digit ratio     (digits / total chars)
 *   [257]     upper ratio     (uppercase / total chars)
 *   [258]     special ratio   (non-alphanumeric non-space / total chars)
 *   [259]     whitespace ratio (spaces+tabs+newlines / total chars)
 *
 * The 4 char-ratio features give the model a fighting chance against
 * completely unknown input formats (binary blobs, pure digits, etc.)
 */
static void extract_features(const char* text, float* vec) {
    size_t len = strlen(text);
    if (len == 0) return;

    /* Trigram counts */
    for (size_t i = 0; i + 2 < len; i++) {
        int idx = hash_trigram(text[i], text[i+1], text[i+2]);
        vec[idx] += 1.0f;
    }

    /* Normalize trigram section */
    float sum = 0.0f;
    for (int i = 0; i < 256; i++) sum += vec[i];
    if (sum > 0.0f) {
        for (int i = 0; i < 256; i++) vec[i] /= sum;
    }

    /* Char-ratio features */
    float digits = 0, uppers = 0, specials = 0, spaces = 0;
    for (size_t i = 0; i < len; i++) {
        unsigned char c = (unsigned char)text[i];
        if (c >= '0' && c <= '9')          digits++;
        else if (c >= 'A' && c <= 'Z')     uppers++;
        else if (c == ' ' || c == '\t' ||
                 c == '\n' || c == '\r')   spaces++;
        else if (c > 32 && c < 127 &&
                 !(c >= 'a' && c <= 'z'))  specials++;
    }
    float n = (float)len;
    vec[256] = digits   / n;
    vec[257] = uppers   / n;
    vec[258] = specials / n;
    vec[259] = spaces   / n;
}

dsmil_classification_t dsmil_micro_model_infer(
    const dsmil_model_context_t* ctx,
    float out_scores[DSMIL_MODEL_NUM_CLASSES])
{
    if (!ctx || !out_scores) return CLASS_UNKNOWN;

    /* --- HARD RULE: no job data at all → UNKNOWN, no guessing --- */
    if (ctx->target_artifact[0] == '\0' &&
        ctx->pre_context[0]     == '\0' &&
        ctx->post_context[0]    == '\0') {
        for (int i = 0; i < DSMIL_MODEL_NUM_CLASSES; i++) out_scores[i] = 0.0f;
        return CLASS_UNKNOWN;
    }

    /* 1. Feature Extraction */
    float x[DSMIL_MODEL_INPUT_DIM] = {0};
    extract_features(ctx->pre_context,      x);
    extract_features(ctx->post_context,     x);
    extract_features(ctx->target_artifact,  x);

    /* 2. Hidden Layer: Dense + ReLU */
    float hidden[DSMIL_MODEL_HIDDEN_DIM] = {0};
    for (int i = 0; i < DSMIL_MODEL_HIDDEN_DIM; i++) {
        float val = MODEL_B1[i];
        for (int j = 0; j < DSMIL_MODEL_INPUT_DIM; j++) {
            val += x[j] * MODEL_W1[j][i];
        }
        hidden[i] = val > 0.0f ? val : 0.0f; /* ReLU */
    }

    /* 3. Output Layer: Dense */
    float max_logit = -1e9f;
    int best_class = 0;
    for (int i = 0; i < DSMIL_MODEL_NUM_CLASSES; i++) {
        float val = MODEL_B2[i];
        for (int j = 0; j < DSMIL_MODEL_HIDDEN_DIM; j++) {
            val += hidden[j] * MODEL_W2[j][i];
        }
        out_scores[i] = val;
        if (val > max_logit) {
            max_logit = val;
            best_class = i;
        }
    }

    /* 4. Softmax (numerically stable) */
    float exp_sum = 0.0f;
    for (int i = 0; i < DSMIL_MODEL_NUM_CLASSES; i++) {
        out_scores[i] = expf(out_scores[i] - max_logit);
        exp_sum += out_scores[i];
    }
    for (int i = 0; i < DSMIL_MODEL_NUM_CLASSES; i++) {
        out_scores[i] /= exp_sum;
    }

    /* 5. Confidence gate — no hallucination */
    if (out_scores[best_class] < DSMIL_CONFIDENCE_THRESHOLD) {
        return CLASS_UNKNOWN;
    }

    return (dsmil_classification_t)best_class;
}
